import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount, useConnect, useDisconnect } from 'wagmi'
import Image from 'next/image'
import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { SocialConnect } from '../components/SocialConnect';
import { useState, useEffect } from 'react';

// Server Component:


const Home: NextPage = () => {

  const { isConnected } = useAccount()
  const { connect, connectors, error, isLoading, pendingConnector } =
    useConnect()
  const { disconnect } = useDisconnect({
    onSuccess(data) {
      console.log('Success', data)
      // Clear local storage
      localStorage.clear();

      // Clear session storage
      sessionStorage.clear();
    },
  })
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  return (
    <div className={styles.socialcontainer}>
      <Head>
        <title>Porta App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="Bridging the Gap, Empower Your Wallet!"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      {domLoaded && (

      <main className={styles.main}>
        {!isConnected &&
          <h1 className={styles.title}>
          Welcome to
          <Link href="/">
            <Image
                src="/porta-logo.png"
                alt="Porta Logo"
                width={213}
                height={87.5}
              />
          </Link>
          </h1>
        }
        {isConnected &&
          <Link href="/">
            <Image
                src="/porta-logo.png"
                alt="Porta Logo"
                width={213}
                height={87.5}
              />
          </Link>
        }

        {!isConnected &&
          <p className={styles.description}>
            Get started connecting your wallet!
          </p>
        }

        <ConnectButton />
        {isConnected &&
        <div className={styles.socialBotSubscription}>
          Social Bot Subscription
        </div>
        }
        { isConnected &&  <SocialConnect platform="telegram" botId="1" name="Revoke Bot" url={`t.me/porta_eth_bot`} isConnected={false}/>}
        { isConnected &&  <SocialConnect platform="telegram" botId="2" name="Signal Buy Bot" url={`t.me/signalBuy_bot`} isConnected={false}/>}
        {/* <Link href="/submitTx?uuid=34f49b2b-08f3-41ba-b327-7785eabb542f">
          <h1>Test Transaction</h1>
        </Link> */}
      </main>
      )}
    </div>
  );
};

export default Home;
